package pbl2.sub119.backend.party.enumerated;

public enum PartyHistoryEventType {
    PARTY_CREATED,
    MEMBER_JOINED,
    RECRUIT_STATUS_CHANGED,
    OPERATION_STATUS_CHANGED,

    MATCH_WAITING_REGISTERED,
    MATCH_WAITING_CANCELED,
    AUTO_MATCHED,
    VACANCY_OPENED
}