package pbl2.sub119.backend.notification.enumerated;

public enum NotificationType {

    // 파티 매칭
    PARTY_MATCHED,
    HOST_PARTY_MATCHED,

    // 결제 / 정산
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    SETTLEMENT_COMPLETED,
    SETTLEMENT_SKIPPED_PAYMENT_FAILED,
    TEST_CARD_PAYMENT_NOTICE,

    // 파티장 provision
    HOST_PROVISION_REQUIRED,
    HOST_PROVISION_REMINDER,
    HOST_PROVISION_TIMEOUT_TERMINATED,
    HOST_PROVISION_DELAYED_NOTICE,

    // 파티원 provision
    PROVISION_ACCOUNT_SHARED_REQUIRED,
    PROVISION_INVITE_CODE_REQUIRED,
    PROVISION_ACCOUNT_SHARED_REMINDER,
    PROVISION_INVITE_ACCEPT_REQUIRED,
    MEMBER_PROVISION_TIMEOUT_NOTICE,

    // 파티 종료 / 재매칭
    PARTY_TERMINATED,
    MEMBER_AUTO_REMATCH_STARTED,

    // 동시접속 제어
    CONCURRENT_WARNING_1,
    HOST_ACTION_REQUIRED_24H,
    HOST_URGENT_PASSWORD_CHANGE,
    HOST_RENOTIFY,
    PARTY_DISSOLVING,
    CREDENTIALS_UPDATED,
    DEVICE_ALERT,
    DEVICE_CHECK_REQUEST,
    DEVICE_CONFIRMED_MINE,
    PARTY_DISSOLVED_FINAL
}