package pbl2.sub119.backend.party.common.enumerated;

public enum PartyHistoryEventType {
    PARTY_CREATED,
    MEMBER_JOINED,
    RECRUIT_STATUS_CHANGED,
    OPERATION_STATUS_CHANGED,

    MATCH_WAITING_REGISTERED,
    MATCH_WAITING_CANCELED,
    AUTO_MATCHED,
    VACANCY_OPENED,

    LEAVE_RESERVED,
    LEAVE_RESERVATION_CANCELED,
    MEMBER_LEFT,

    HOST_TRANSFER_REQUESTED,
    HOST_TRANSFER_ACCEPTED,
    HOST_TRANSFER_REJECTED,
    HOST_TRANSFER_COMPLETED,

    PARTY_TERMINATION_PENDING,
    PARTY_TERMINATED,

    PAYMENT_EXECUTION_SUCCEEDED,
    PAYMENT_EXECUTION_FAILED,

    MEMBER_PROVISION_TIMEOUT,
    PARTY_PROVISION_DISSOLVED,
}